<div class="card-wide mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title">
    </div>
    <div class="mdl-card__actions mdl-card--border">
        <a id="user-page" href="<?php echo $this->url('admin/users/edit', array('id' => $this->identity()->getId())); ?>" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" style="width: 93%">
            <?php if($_SESSION['Admin']['provider'] == 'google' || $_SESSION['User']['provider'] == 'google'): ?>
                <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                    <path fill="red" d="M23,11H21V9H19V11H17V13H19V15H21V13H23M8,11V13.4H12C11.8,14.4 10.8,16.4 8,16.4C5.6,16.4 3.7,14.4 3.7,12C3.7,9.6 5.6,7.6 8,7.6C9.4,7.6 10.3,8.2 10.8,8.7L12.7,6.9C11.5,5.7 9.9,5 8,5C4.1,5 1,8.1 1,12C1,15.9 4.1,19 8,19C12,19 14.7,16.2 14.7,12.2C14.7,11.7 14.7,11.4 14.6,11H8Z" />
                </svg>
            <?php elseif($_SESSION['Admin']['provider'] == 'facebook' || $_SESSION['User']['provider'] == 'facebook'): ?>
                <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                    <path fill="blue" d="M17,2V2H17V6H15C14.31,6 14,6.81 14,7.5V10H14L17,10V14H14V22H10V14H7V10H10V6A4,4 0 0,1 14,2H17Z" />
                </svg>
            <?php endif; ?>
            <?php echo $this->identity()->getName(); ?>
        </a>
        <a href="<?php echo $this->url('app/auth/logout'); ?>" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect mdl-color--red mdl-color-text--white" style="width: 93%; margin-top: 1%"><?php echo $this->translate('Logout', 'default', $_SESSION['translate']); ?></a>
    </div>
</div>

<style>
    .card-wide > .mdl-card__title {
        color: #fff;
        background: url('<?php echo $this->identity()->getAvatarId() ? $this->identity()->getAvatarId()->getPath() : 'img/default-user.png'; ?>') center / cover no-repeat;
        background-size: 200px;
        min-height: 235px;
    }
</style>