<?php

/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
if (php_sapi_name() == "cli") {
    defined('APPLICATION_ENV') || define('APPLICATION_ENV', 'dev-paml');
}

$modules = array(
    'Application',
    'DoctrineModule',
    'DoctrineORMModule',
    'Api',
    'Admin',
);

return array(
    'modules' => $modules,
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
        ),
        'config_glob_paths' => array(
            'config/autoload/{{,*.}global,{,*.}local}.php',
            'config/autoload/' . APPLICATION_ENV . '/{,*.}{global,local}.php',
        ),
    ),
);
